name: Extrair legendas
description: Salve a legenda do vídeo
title: "Extrair legendas"
labels: ["legendas"]
body:
  - type: input
    id: url
    attributes:
      label: URL
      description: URL do vídeo
    validations:
      required: true
